---
title: "Análisis de datos en RStudio"
author: 
  - name: Apellidos y Nombres
  - name: Grupo #
format: html
---

# 3 Actividades para el Portafolio Electrónico de las Actividades de Enseñanza y Aprendizaje

## Semana 01

Sube un documento en word (.docx):

1.  Que muestre capturas de pantalla de la interaz de RStudio (contará como evidencia de la instalación de R y RStudio)

2.  Que incluya capturas de pantalla del proyecto de RStudio y las carpetas pertinentes del proyecto.

## Semana 02

En este documento de Quarto (.qmd)

1.  Haz uso de 3 funciones distintas a las usadas en esta sesión y resume su función (Explica con tus propias palabras su utilidad)

2.  Realiza la descarga y activación (carga de librerías) de 2 paquetes distintos a los instalados en esta sesión

3.  Escribe código en R para la importación del dataset asignado a tu grupo de práctica.

## Semana 03

En este documento de Quarto (.qmd)

1.  Escribe código de r para la limpieza de datos al menos en 2 aspectos usando la base de datos asignado a tu grupo.

2.  Escribe código de r para la tranformación de al menos 2 variables usando la base de datos asignada a tu grupo.

## Semana 04

En este documento de Quarto (.qmd)

1.  Escribe código de r para la limpieza de datos al menos en 2 aspectos usando la base de datos asignado a tu grupo.

2.  Escribe código de r para la tranformación de al menos 2 variables usando la base de datos asignada a tu grupo.

## Semana 05

En este documento de Quarto (.qmd)
